hyperparams:
    num_hidden_layers: 2
    hidden_dims: 16,32
    learning_rates: 0.001,0.005
    nums_epochs: 1000,2000
    l2_coeffs: 0.0005,0.005,0.05
    dropout_rates: 0,0.1,0.2
    x_l1_coeffs: None
    x_ent_coeffs: None
    edge_l1_coeffs: None
    edge_ent_coeffs: None